### PR TITLE
Developmentrouter v5

### PR DESCRIPTION
**Pull request by andre4meister**

### CODE REVIEW

**Review by IvanMykytyn — COMMENTED** [review]
image
Component 'PrivateRoute' isn't fully pure. I think you need to change the prop type to something more generic.

**Review by IvanMykytyn — APPROVED** [review]
I think you should add 'not found' route

**Comment by andre4meister** [comment]
> image Component 'PrivateRoute' isn't fully pure. I think you need to change the prop type to something more generic.

I could create some collective type where are described props for all components which use this HOC, would it be okay? )

**Review by IvanMykytyn — CHANGES_REQUESTED** [review]
image
Component 'PrivateRoute' isn't fully pure. I think you need to change the prop type to something more generic.

**Comment by VanekCheck** [comment]
> image Component 'PrivateRoute' isn't fully pure. I think you need to change the prop type to something more generic.



> image Component 'PrivateRoute' isn't fully pure. I think you need to change the prop type to something more generic.

**Comment by VanekCheck** [comment]
Just testing

**Pull request closed without merging**
